export const domains = [
  { value: 'oil-gas', label: 'Oil & Gas' },
  { value: 'fintech', label: 'Financial Technology' },
  { value: 'healthcare', label: 'Healthcare' },
  { value: 'ecommerce', label: 'E-Commerce' },
  { value: 'manufacturing', label: 'Manufacturing' },
  { value: 'telecom', label: 'Telecommunications' },
  { value: 'retail', label: 'Retail' },
  { value: 'education', label: 'Education' },
  { value: 'software', label: 'Software Development' },
  { value: 'gaming', label: 'Gaming' },
  { value: 'automotive', label: 'Automotive' },
  { value: 'logistics', label: 'Logistics & Supply Chain' },
  { value: 'media', label: 'Media & Entertainment' },
  { value: 'travel', label: 'Travel & Hospitality' },
  { value: 'real-estate', label: 'Real Estate' },
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'energy', label: 'Energy' },
  { value: 'government', label: 'Government' },
  { value: 'other', label: 'Other' },
];
