agents:
  epic_strategist:
    prompt_file: "prompts/epic_strategist.txt"
  feature_decomposer_agent:
    prompt_file: "prompts/feature_decomposer_agent.txt"
  user_story_decomposer_agent:
    prompt_file: "prompts/user_story_decomposer.txt"
  decomposition_agent:
    prompt_file: "prompts/decomposition_agent.txt"  # Legacy support
  developer_agent:
    prompt_file: "prompts/developer_agent.txt"
    estimation_unit: "hours"
  qa_lead_agent:
    prompt_file: "prompts/qa_lead_agent.txt"
    timeout_seconds: 180  # Longer timeout for QA operations
    
    # Test organization requirements
    test_organization:
      enforce_completeness: true  # Ensure all features have plans, all stories have suites
      require_test_plan_per_feature: true
      require_test_suite_per_story: true
      require_test_case_linking: true
      validate_ado_integration: true
    
    # Azure DevOps Test Management integration
    ado_integration:
      enabled: true
      area_path: "Grit"  # Override default area path detection
      auto_create_test_plans: true
      auto_create_test_suites: true
      auto_link_test_cases: true
      update_test_results: true
      
      # Autonomous testing configuration
      autonomous_testing:
        use_requirement_based_suites: true  # Use requirement-based instead of static suites
        auto_generate_tags: true            # Automatically tag test cases for filtering
        enable_automation_metadata: true    # Add automation readiness fields
        intelligent_test_distribution: true # Add metadata for AI/human agent distribution
        enforce_clear_preconditions: true   # Require clear preconditions for autonomous execution
    
    sub_agents:
      test_plan_agent:
        prompt_file: "prompts/test_plan_agent.txt"
        timeout_seconds: 120
        min_test_plans_per_feature: 1
      test_suite_agent:
        prompt_file: "prompts/test_suite_agent.txt"
        timeout_seconds: 90
        min_test_suites_per_story: 1
      test_case_agent:
        prompt_file: "prompts/test_case_agent.txt"
        test_case_format: "gherkin"
        timeout_seconds: 180  # Longest timeout for complex test case generation
        min_test_cases_per_story: 3  # Minimum test cases per user story
  backlog_sweeper_agent:
    enabled: true
    
    # Targeted sweeps (supervisor-initiated after each stage)
    targeted_sweeps:
      enabled: true
      immediate_remediation: true
      max_retries_per_stage: 3
      stages:
        - epic_strategist
        - feature_decomposer_agent  
        - user_story_decomposer_agent
        - developer_agent
        - qa_lead_agent
    
    # Scheduled sweeps (autonomous recurring health checks)
    scheduled_sweeps:
      enabled: true
      schedule: "0 12 * * *"  # Daily at 12:00 UTC (cron format)
      comprehensive: true
      report_only: false  # Set to true to only report, not attempt remediation
    
    acceptance_criteria:
      min_criteria_count: 3
      max_criteria_count: 8
      require_bdd_format: true
      require_functional_and_nonfunctional: true
    severity_thresholds:
      critical_notification_count: 5  # Send notifications when this many high-priority issues found
      max_discrepancies_per_run: 100  # Cap reporting to avoid overwhelming supervisor

workflow:
  sequence:
    - epic_strategist
    - feature_decomposer_agent
    - user_story_decomposer_agent
    - developer_agent
    - qa_lead_agent
  
  # Quality validation options
  validation:
    immediate_validation: true  # Run targeted sweeps after each stage
    max_retries_per_stage: 3   # How many times to retry a stage if issues found
    fail_fast: false          # Stop workflow on first stage failure
  
  # Output limits (production mode - unlimited for full backlog generation)
  limits:
    max_epics: null                    # null = unlimited epics
    max_features_per_epic: null        # null = unlimited features per epic
    max_user_stories_per_feature: null # null = unlimited user stories per feature
  
  output_format: "azure_devops"
  
  # Parallel processing configuration
  parallel_processing:
    enabled: true  # Re-enabled after fixing asyncio.to_thread issue
    max_workers: 4
    rate_limit_per_second: 10
    feature_decomposition: true
    user_story_decomposition: true
    task_generation: true
    qa_generation: true
    qa_sub_agent_parallel: true  # Enable parallel processing within QA sub-agents

notifications:
  enabled: true
  channels: [teams, email]
  summary_report:
    format: markdown
    send_to:
      - kevin.tran@c4workx.com
      - thaogtran@gmail.com

# Work item limits configuration
work_item_limits:
  enabled: true
  
  # Maximum number of work items per job (null for unlimited)
  max_epics: 2
  max_features_per_epic: 3
  max_user_stories_per_feature: 5
  max_tasks_per_user_story: 5
  max_test_cases_per_user_story: 5
  
  # Preset configurations for quick setup
  presets:
    small:
      max_epics: 2
      max_features_per_epic: 3
      max_user_stories_per_feature: 4
      max_tasks_per_user_story: 4
      max_test_cases_per_user_story: 3
    medium:
      max_epics: 3
      max_features_per_epic: 4
      max_user_stories_per_feature: 5
      max_tasks_per_user_story: 5
      max_test_cases_per_user_story: 4
    large:
      max_epics: 5
      max_features_per_epic: 6
      max_user_stories_per_feature: 6
      max_tasks_per_user_story: 6
      max_test_cases_per_user_story: 5
    unlimited:
      max_epics: null
      max_features_per_epic: null
      max_user_stories_per_feature: null
      max_tasks_per_user_story: null
      max_test_cases_per_user_story: null