project:
  name: "Agile Backlog Automation"
  default_area_path: "Backlog Automation\\Ride Sharing"
  default_iteration_path: "Backlog Automation\\Sprint 2025-07"

domains:
  supported:
    - "software_development"
    - "fintech"
    - "ecommerce"
    - "healthcare"
    - "education"
    - "shipping_logistics"
    - "oil_gas"
  default: "software_development"

agents:
  epic_strategist:
    prompt_file: "prompts/epic_strategist.txt"
  decomposition_agent:
    prompt_file: "prompts/decomposition_agent.txt"
  developer_agent:
    prompt_file: "prompts/developer_agent.txt"
    estimation_unit: "hours"
  qa_tester_agent:
    prompt_file: "prompts/qa_tester_agent.txt"
    test_case_format: "gherkin"
  backlog_sweeper_agent:
    enabled: true
    schedule: "0 12 * * *"  # Daily at 12:00 UTC (cron format)
    acceptance_criteria:
      min_criteria_count: 3
      max_criteria_count: 8
      require_bdd_format: true
      require_functional_and_nonfunctional: true
    severity_thresholds:
      critical_notification_count: 5  # Send notifications when this many high-priority issues found
      max_discrepancies_per_run: 100  # Cap reporting to avoid overwhelming supervisor

workflow:
  sequence:
    - epic_strategist
    - decomposition_agent
    - developer_agent
    - qa_tester_agent
  output_format: "azure_devops"

notifications:
  enabled: true
  channels: [teams, email]
  summary_report:
    format: markdown
    send_to:
      - kevin.tran@c4workx.com
      - thaogtran@gmail.com