domains:
  supported:
    - "software_development"
    - "fintech"
    - "ecommerce"
    - "healthcare"
    - "education"
    - "shipping_logistics"
    - "oil_gas"
  default: "oil_gas"

agents:
  epic_strategist:
    prompt_file: "prompts/epic_strategist.txt"
  feature_decomposer_agent:
    prompt_file: "prompts/feature_decomposer_agent.txt"
  user_story_decomposer_agent:
    prompt_file: "prompts/user_story_decomposer.txt"
  decomposition_agent:
    prompt_file: "prompts/decomposition_agent.txt"  # Legacy support
  developer_agent:
    prompt_file: "prompts/developer_agent.txt"
    estimation_unit: "hours"
  qa_tester_agent:
    prompt_file: "prompts/qa_tester_agent.txt"
    test_case_format: "gherkin"
  backlog_sweeper_agent:
    enabled: true
    
    # Targeted sweeps (supervisor-initiated after each stage)
    targeted_sweeps:
      enabled: true
      immediate_remediation: true
      max_retries_per_stage: 3
      stages:
        - epic_strategist
        - feature_decomposer_agent  
        - user_story_decomposer_agent
        - developer_agent
        - qa_tester_agent
    
    # Scheduled sweeps (autonomous recurring health checks)
    scheduled_sweeps:
      enabled: true
      schedule: "0 12 * * *"  # Daily at 12:00 UTC (cron format)
      comprehensive: true
      report_only: false  # Set to true to only report, not attempt remediation
    
    acceptance_criteria:
      min_criteria_count: 3
      max_criteria_count: 8
      require_bdd_format: true
      require_functional_and_nonfunctional: true
    severity_thresholds:
      critical_notification_count: 5  # Send notifications when this many high-priority issues found
      max_discrepancies_per_run: 100  # Cap reporting to avoid overwhelming supervisor

workflow:
  sequence:
    - epic_strategist
    - feature_decomposer_agent
    - user_story_decomposer_agent
    - developer_agent
    - qa_tester_agent
  
  # Quality validation options
  validation:
    immediate_validation: true  # Run targeted sweeps after each stage
    max_retries_per_stage: 3   # How many times to retry a stage if issues found
    fail_fast: false          # Stop workflow on first stage failure
  
  # Output limits (set to null for unlimited production use)
  limits:
    max_epics: null           # null = unlimited (production mode)
    max_features_per_epic: null  # null = unlimited (production mode)  
    max_user_stories_per_feature: null  # null = unlimited
  
  output_format: "azure_devops"

notifications:
  enabled: true
  channels: [teams, email]
  summary_report:
    format: markdown
    send_to:
      - kevin.tran@c4workx.com
      - thaogtran@gmail.com