project:
  name: "Agile Backlog Automation"
  default_area_path: "Backlog Automation\\Data Visualization"
  default_iteration_path: "Backlog Automation\\Sprint 2025-07"

domains:
  supported:
    - "software_development"
    - "fintech"
    - "ecommerce"
    - "healthcare"
    - "education"
    - "shipping_logistics"
    - "oil_gas"
  default: "oil_gas"

agents:
  epic_strategist:
    prompt_file: "prompts/epic_strategist.txt"
  decomposition_agent:
    prompt_file: "prompts/decomposition_agent.txt"
  developer_agent:
    prompt_file: "prompts/developer_agent.txt"
    estimation_unit: "hours"
  qa_tester_agent:
    prompt_file: "prompts/qa_tester_agent.txt"
    test_case_format: "gherkin"

workflow:
  sequence:
    - epic_strategist
    - decomposition_agent
    - developer_agent
    - qa_tester_agent
  output_format: "azure_devops"

notifications:
  enabled: true
  channels: [teams, email]
  summary_report:
    format: markdown
    send_to:
      - kevin.tran@c4workx.com
      - thaogtran@gmail.com